/*
 * generated by Xtext
 */
package nl.marsrover;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends nl.marsrover.AbstractDSLRuntimeModule {

}
