/**
 * generated by Xtext
 */
package nl.marsrover.ui.contentassist;

import nl.marsrover.ui.contentassist.AbstractDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
