/*
* generated by Xtext
*/
package nl.marsrover;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return nl.marsrover.ui.internal.DSLActivator.getInstance().getInjector("nl.marsrover.DSL");
	}
	
}
